### ISSUE TITLE
Module AppRegistry is not registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by razaadeel** [costvin15/react-native-moodlemobile#15]
Hello, 
I have clone this app app and after installing all modules, when I run react-native run-android it is showing error:
Module AppRegistry is not registered callable module (calling runApplication)

**Comment by amysticool** [comment]
Hello, 
I have same problem, did you found a solve ? help please.

here is the debug output :
`[Fri Oct 22 2021 18:38:27.425]  BUNDLE  ./index.js

[Fri Oct 22 2021 18:39:05.218]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\Checkbox\Checkbox.js -> node_modules\react-native-paper\lib\module\components\Checkbox\CheckboxItem.js -> node_modules\react-native-paper\lib\module\components\Checkbox\Checkbox.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.222]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\FAB\FAB.js -> node_modules\react-native-paper\lib\module\components\FAB\FABGroup.js -> node_modules\react-native-paper\lib\module\components\FAB\FAB.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.223]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\RadioButton\RadioButton.js -> node_modules\react-native-paper\lib\module\components\RadioButton\RadioButtonItem.js -> node_modules\react-native-paper\lib\module\components\RadioButton\RadioButton.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.223]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\Appbar\Appbar.js -> node_modules\react-native-paper\lib\module\components\Appbar\AppbarHeader.js -> node_modules\react-native-paper\lib\module\components\Appbar\Appbar.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.224]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\ToggleButton\ToggleButton.js -> node_modules\react-native-paper\lib\module\components\ToggleButton\ToggleButtonRow.js -> node_modules\react-native-paper\lib\module\components\ToggleButton\ToggleButton.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.225]  WARN     Require cycle: src\api\helper.js -> src\events\index.js -> src\events\course.js -> src\api\helper.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.225]  WARN     Require cycle: src\api\helper.js -> src\events\index.js -> src\events\user.js -> src\api\helper.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.226]  WARN     Require cycle: src\api\helper.js -> src\events\index.js -> src\events\module.js -> src\api\helper.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.227]  WARN     Require cycle: node_modules\rn-fetch-blob\index.js -> node_modules\rn-fetch-blob\polyfill\index.js -> node_modules\rn-fetch-blob\polyfill\Blob.js -> node_modules\rn-fetch-blob\index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.229]  WARN     Require cycle: node_modules\rn-fetch-blob\index.js -> node_modules\rn-fetch-blob\polyfill\index.js -> node_modules\rn-fetch-blob\polyfill\XMLHttpRequest.js -> node_modules\rn-fetch-blob\index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.230]  WARN     Require cycle: node_modules\rn-fetch-blob\index.js -> node_modules\rn-fetch-blob\polyfill\index.js -> node_modules\rn-fetch-blob\polyfill\Fetch.js -> node_modules\rn-fetch-blob\index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.[Fri Oct 22 2021 18:39:05.231]  ERROR    TypeError: Super expression must either be null or a function
[Fri Oct 22 2021 18:39:05.231]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Fri Oct 22 2021 18:39:05.233]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

**Comment by costvin15** [comment]
Hi @razaadeel, @amysticool. This really is a bug, I am now checking for a solution as soon as possible.
Thank you for reporting

**Comment by costvin15** [comment]
This bug has been fixed with the pull request #18 
I am closing the issue
